apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    url: http://clickhouse:8123
    database: rec_monitor
    editable: true
